#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link      http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license   http://www.yiiframework.com/license/
 */


require __DIR__ . '/../../vendor/autoload.php';
require __DIR__ . '/../../env.php';

$dotEnv = new Dotenv\Dotenv(__DIR__ . '/../');
if(getenv('YII_ENV') !== 'prod') {
    $dotEnv->load();
}


defined('YII_DEBUG') or define('YII_DEBUG', (bool)env('YII_DEBUG'));
defined('YII_ENV') or define('YII_ENV', env('YII_ENV'));

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require __DIR__ . '/../../vendor/yiisoft/yii2/Yii.php';

$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/../common/etc/config/main.php',
    require __DIR__ . '/etc/config/main.php'
);

require __DIR__ . '/../common/bootstrap.php';

$application = new yii\console\Application($config);
$exitCode    = $application->run();
exit($exitCode);
